### PR TITLE
fix(toggle-button): wrong state

### LINKED ISSUE #35: [button] Some ToggleButton bugs
## Button's active state is inverted

When I set the active state of a toggle button e.g. `active={isEnabled}`, it won't toggle the button, but when I negate the variable (e.g. `active={!isEnabled}`) it will work.

## `onClick` is triggered outside of button

If I click outside of the rendered button but still inside its containing div, the button will still click. **Solution:** Move the `onClick` away from the containing div and into each render prop.

### PR DESCRIPTION
**Pull request by reyhansofian**
Closes #35

This bug caused by the wrong use of `getDerivedStateFromProps`. Actually, we don't need that method to maintain the component state.

### CODE REVIEW

File: packages/button/src/components/ToggleButton.tsx [hunk 1]
```diff
@@ -15,16 +15,10 @@ class ToggleButton extends React.Component<
...
 > {
-  static defaultProps = {
-    active: false
+  state = {
+    active: this.props.active || false
   };
 
-  static getDerivedStateFromProps(props: ToggleButtonProps) {
-    return {
-      active: props.active
```
Comment (reyhansofian) [inline packages/button/src/components/ToggleButton.tsx]: since `getDerivedStateFromProps` always run right before `render`, the `props.active` will always overwrite the current state

**Comment by reyhansofian** [comment]
will do
